### ISSUE TITLE
debug does't find the file

### ISSUE THREAD

**Issue by dancespiele** [rtbenfield/vscode-jest-test-adapter#19] opened 2018-12-31 10:47 UTC
hello I try to debug a test but the point is that it doesn't found the file however the path which it try to find the file is right

my config file:
```json
{
  "configurations": [
        {
            "name": "Debug Jest Tests",
            "type": "node",
            "request": "attach",
            "sourceMaps": true,
            "cwd": "${workspaceFolder}",
            "port": 9229,
            "stopOnEntry": false
        }
    ]
}
```

issue when debug is running:
```
M-23:sg-sdk francisco$ cd /Users/francisco/projects/sg-sdk ; /usr/local/bin/node --inspect-brk=35158 node_modules/jest/bin/jest.js --runInBand --testPathPattern "\"(/Users/francisco/projects/sg-sdk/test/tools/helpers\.test\.js)\"" --testNamePattern "\"(^Helpers deepCopy should get the copy of the object$)\""
Debugger listening on ws://127.0.0.1:35158/58e842a0-b802-41c2-bed4-b814fdb99274
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
No tests found
In /Users/francisco/projects/sg-sdk
  206 files checked.
  testMatch: **/__tests__/**/*.js?(x),**/?(*.)+(spec|test).js?(x) - 6 matches
  testPathIgnorePatterns: /node_modules/ - 206 matches
Pattern: "(/Users/francisco/projects/sg-sdk/test/tools/helpers\.test\.js)" - 0 matches
Waiting for the debugger to disconnect...
Killed: 9
```

**Comment by rtbenfield** [comment] 2019-01-08 03:20
I think I have found and addressed this issue. Could you please try the latest version (0.1.2) and see if that resolves it for you? If not, could you provide some details about your environment (ex. OS, Jest version, and, if applicable, project template).?

**Comment by dancespiele** [comment] 2019-01-09 12:55
hello @rtbenfield sorry for may delay answer, with the last version it works. Now only small issue is that it doesn't pause in the same point where I put the breakpoint and it is changed in some previous line but It can work with it, it is not important and maybe the issue come from how babel transform it. Thank you to resolve the blocked problem.

**Comment by rtbenfield** [comment] 2019-01-12 02:11
@dancespiele can you provide an example repo that reproduces the issue you are still seeing? It *should* be working even with transpiling, but there may be some situations that are not properly handled yet.

**Comment by rtbenfield** [comment] 2019-01-12 02:13
Since the problem defined here was resolved with the latest version, I am going to go ahead and close this issue. If you are able to provide an example of the other problem you are experiencing, please open a new issue. Just trying to keep things clean 😃

**Closed by rtbenfield** 2019-01-12 02:13 UTC
Labels: bug
